name: Rodeo (Native)
root: ~/code/rdo-apps/apps/native/
enable_pane_titles: true
pane_title_position: bottom
windows:
  - Server:
      root: ~/code/rdo-apps/apps/native/
      panes:
        - Server:
            - nr start --clear
  - Vim:
      root: ~/code/rdo-apps/apps/native/
      layout: f8a9,187x75,0,0[187x58,0,0,18,187x16,0,59,19]
      panes:
        - Vim:
          - vim

on_project_exit: pkill -9 -f "node.*$(basename $(pwd))" 2>/dev/null || true
