name: starframe
root: ~/code/starframe
windows:
  - claude:
      panes:
        - claude -c --dangerously-skip-permissions
  - dev:
      panes:
        - nr dev
  - editor:
      panes:
        - nvim
