#!/usr/bin/env sh

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa
#

yabai -m space 1 --label dev
yabai -m space 2 --label social
yabai -m space 3 --label media

# Window rules
yabai -m rule --add app="^kitty$" space=web
yabai -m rule --add app="^Brave Browser$" space=web
yabai -m rule --add app="^Slack$" space=social
yabai -m rule --add app="^Signal$" space=social
yabai -m rule --add app="^WhatsApp$" space=social
yabai -m rule --add app="^Discord$" space=social
yabai -m rule --add app="^Spotify$" space=media

# Float apps
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^Raycast$" manage=off
yabai -m rule --add app="^Activity Monitor$" manage=off
yabai -m rule --add app="^1Password$" manage=off
yabai -m rule --add app="^Cron$" manage=off

# Global settings
yabai -m config mouse_follows_focus off
yabai -m config focus_follows_mouse on
yabai -m config window_origin_display default
yabai -m config window_placement second_child
yabai -m config window_topmost off
yabai -m config window_shadow off
yabai -m config window_opacity on
yabai -m config window_opacity_duration 0.0
yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 1.0
yabai -m config window_animation_duration 0.0
yabai -m config window_border on
yabai -m config window_border_width 3
yabai -m config window_border_blur off
yabai -m config window_border_radius 12
yabai -m config active_window_border_topmost off
yabai -m config active_window_border_color 0xffcad3f5
yabai -m config normal_window_border_color 0xff24273a
ayabai -m config insert_feedback_color 0xfff5a97f
yabai -m config split_ratio 0.50
yabai -m config split_type auto
yabai -m config auto_balance on
yabai -m config mouse_modifier ctrl
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize

# General space settings
yabai -m config layout bsp
yabai -m config top_padding 5
yabai -m config bottom_padding 5
yabai -m config left_padding 5
yabai -m config right_padding 5
yabai -m config window_gap 5

# Auto-update from HEAD via Brew
# https://github.com/koekeishiya/yabai/wiki/Tips-and-tricks#auto-updating-from-head-via-brew
YABAI_CERT=yabai-cert sh -c "$(curl -fsSL "https://git.io/update-yabai")" &

echo "yabai configuration loaded.."
