disableStartupPopups: true
promptToReturnFromSubprocess: false
gui:
  showRandomTip: false
  showIcons: true
  theme:
      selectedLineBgColor:
        - default
      selectedRangeBgColor:
        - default
