disableStartupPopups: true
promptToReturnFromSubprocess: false
gui:
  showRandomTip: false
  showIcons: true
  theme:
    lightTheme: false
    activeBorderColor:
      - '#FE915E'
      - bold
    inactiveBorderColor:
      - '#7A7C7E' # Text
    selectedLineBgColor:
      - '#1E222A' # Surface0
