disableStartupPopups: true
promptToReturnFromSubprocess: false
gui:
  showRandomTip: false
  showIcons: true
  theme:
      selectedLineBgColor:
        - default
        - bold
      selectedRangeBgColor:
        - default
      inactiveBorderColor:
        - white
