disableStartupPopups: true
promptToReturnFromSubprocess: false
gui:
  nerdFontsVersion: '3'
  showRandomTip: false
  theme:
    activeBorderColor:
      - '#FE915E'
      - bold
    inactiveBorderColor:
      - '#7A7C7E' # Text
    selectedLineBgColor:
      - '#1E222A' # Surface0
customCommands:
  - key: 'C'
    context: 'files'
    command: 'git diff --cached | pbcopy; open raycast://ai-commands/git-commit-message && git commit'
    description: 'Raycast AI Commit'
    subprocess: true
