disableStartupPopups: true
promptToReturnFromSubprocess: false
gui:
  nerdFontsVersion: '3'
  showRandomTip: false
  theme:
    activeBorderColor:
      - '#FE915E'
      - bold
    inactiveBorderColor:
      - '#7A7C7E' # Text
    selectedLineBgColor:
      - '#1E222A' # Surface0
