disableStartupPopups: true
promptToReturnFromSubprocess: false
gui:
  nerdFontsVersion: '3'
  showRandomTip: false
  theme:
    activeBorderColor:
      - '#86e1fc'
      - bold
    inactiveBorderColor:
      - '#737aa2' # Surface0
      - bold
    selectedLineBgColor:
      - '#1e2030' # Text
git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never